spring:
#  datasource:
#    url: "jdbc:h2:tcp://localhost/~/dbs/toy_blog"
#    username: "sa"
#    password:
#    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/solvelog"
    username: "solvelog_admin"
    password: "solve1234"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000 #ms
      ssl:
        enabled: false
  #      password:

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: therin234@gmail.com
    password: ${SMTP_PASSWORD}
    properties.mail.smtp:
      auth: true
      timeout: 5000
      starttls.enable: true

logging.level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace

cookie:
  secure: false
  same-site: Lax

cloud:
  aws:
    s3:
      bucket: ${SOLVELOG_BUCKET}
#      bucket: solvelog-local
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${SOLVELOG_ACCESS_KEY}
      secret-key: ${SOLVELOG_SECRET_KEY}


app:
  base-url: http://localhost:5173
