name: deploy SolveLog

on:
  workflow_run:
    workflows: 
      - solvelogCi
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-northeast-2'

      - name: Add GitHub Actions IP
        run: |
          aws ec2 authorize-security-group-ingress \
              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
              --protocol tcp \
              --port 22 \
              --cidr ${{ steps.ip.outputs.ipv4 }}/32
              
      - name: SSH to EC2 & Deploy Updated Images
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/solvelog

            echo "Pull latest images..."
            docker-compose pull

            echo "restart proxyserver container"
            docker-compose up -d nginxproxy

            echo "start Blue Green Deployment"
            IS_BACKENDSERVER1=$(docker ps | grep backendserver1 || true)
            DEFAULT_CONF="/nginx/nginx.conf"
            MAX_RETRIES=20

            check_service() {
              local RETRIES=0
              local URL=$1
              while [ $RETRIES -lt $MAX_RETRIES ]; do
                echo "Checking service at $URL... (attempt: $((RETRIES+1)))"
                sleep 3

                REQUEST=$(curl -s $URL || true)
                if [ -n "$REQUEST" ]; then
                  echo "health check success"
                  return 0
                fi

                RETRIES=$((RETRIES+1))
              done;

              echo "Failed to check service after $MAX_RETRIES attempts."
              return 1
            }

            if [ -z "$IS_BACKENDSERVER1" ]; then
              echo "### BACKENDSERVER2 => BACKENDSERVER1 ###"

              echo "1. Restart Container BACKENDSERVER1"
              docker-compose up -d --remove-orphans backend1

              echo "2. health check"
              if ! check_service "http://127.0.0.1:8080"; then
                echo "BACKENDSERVER1 health check failed"
                exit 1
              fi

              echo "3. reload nginx"
              cp ./nginx/nginx.blue.conf ./nginx/nginx.conf
              docker exec proxyserver nginx -s reload

              echo "4. stop backend2"
              docker-compose stop backend2
              docker-compose rm -f backend2

            else
              echo "### BACKENDSERVER1 => BACKENDSERVER2 ###"

              echo "1. Restart Container BACKENDSERVER2"
              docker-compose up -d --remove-orphans backend2

              echo "2. health check"
              if ! check_service "http://127.0.0.1:8081"; then
                echo "BACKENDSERVER2 health check failed"
                exit 1
              fi

              echo "3. reload nginx"
              cp ./nginx/nginx.green.conf ./nginx/nginx.conf
              docker exec proxyserver nginx -s reload

              echo "4. stop backend1"
              docker-compose stop backend1
              docker-compose rm -f backend1
            fi

            echo "Prune unused images..."
            docker image prune -af || true

            echo "Deployment completed!"

      - name: Remove GitHub Actions IP
        run: |
          aws ec2 revoke-security-group-ingress \
              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
              --protocol tcp \
              --port 22 \
              --cidr ${{ steps.ip.outputs.ipv4 }}/32
